version: "3.8"

services:

  app:
    build:
      context: .
    container_name: smart-clinic-backend
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cms
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: kaungmysql18

      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: prescriptions


  mysql:
    image: mysql:8.0
    container_name: smart-clinic-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: kaungmysql18
      MYSQL_DATABASE: cms
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pkaungmysql18"]
      interval: 10s
      timeout: 5s
      retries: 5


  mongodb:
    image: mongo:6.0
    container_name: smart-clinic-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "--eval",
          "db.runCommand({ ping: 1 })"
        ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  mysql-data:
  mongo-data: